# # MySQL database connection properties
# spring.application.name=gamezxne
# spring.datasource.url=jdbc:mysql://localhost:3306/gamezxne_db
# spring.datasource.username=gamezxne_user
# spring.datasource.password=user1234


# # Hibernate properties
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# # spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# # spring.jpa.properties.hibernate.globally_quoted_identifiers=true



##############the following is for h2###############################



# H2 in-memory database connection properties
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 console settings (optional - to access the H2 console in browser)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console